module.exports = [
  {
    id: 1,
    icon: 'laptop',
    cn: '首页',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    cn: '用户管理',
    name: 'User Manage',
    icon: 'user',
    router: '/user',
  },
  {
    id: 3,
    mpid: -1,
    bpid: 2,
    cn: '用户详情',
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 6,
    bpid: 1,
    cn: '测试',
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    cn: '测试1',
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    cn: '测试2',
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 621,
    bpid: 62,
    mpid: 62,
    cn: '测试21',
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 622,
    bpid: 62,
    mpid: 62,
    cn: '测试22',
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
]
